test1:
	g++ -o test1 tester.cpp operations.cpp  && ./test1
test2:
	g++ -o test2 tester2.cpp operations.cpp  && ./test2
test3:
	g++ -o test3 tester3.cpp operations.cpp  && ./test3
clean:
	rm -f test1 test2 test3